### ISSUE TITLE
Few Interaction Points

### ISSUE THREAD

**Issue by johnvilsack** [SpaceGameDev568/ObstacleMod#1]
1. Ragdolling from getting bopped doesn't trigger vanilla jumppads. Might be out of scope.
2. Getting yeeted from a jumppad into the yeet cannon will not trigger the cannon

**Comment by SpaceGameDev568** [comment]
Being in a ragdolled state can't trigger anything until the player gets up; there's nothing I can do about that since I'm reusing the ragdoll mechanic usually used for getting run over by vehicles. Also, the Yeet Cannon won't trigger unless you stand on the green box and wait 5 seconds for it to launch.
